### ISSUE TITLE
Improve pizza relative UIImageViews

### ISSUE THREAD

**Issue by ramonsaraiva** [ndrsKloss/jake#2]
Currently, these image views:

```swift
@IBOutlet weak var arms: UIImageView!
@IBOutlet weak var ears: UIImageView!
@IBOutlet weak var eyes: UIImageView!
@IBOutlet weak var iris: UIImageView!
@IBOutlet weak var nose: UIImageView!
```

are all being processed separately by an unique function.

Could we generalize this behaviour by adding all "pizza relative" entities into a list of `relativeEntities`?
For that, I would tend to write a structure that would hold an `UIImageView` with relative `X` and `Y` values. Or, if it simplifies, just a tuple of an `UIImageView, X offset, Y offset`.

With that in place, we could possibly have a single function that would process all `relativeEntities`, adjusting their offset based on the pizza location.

Let me know if that makes sense and i'll create a PR for it.

**Comment by ndrsKloss** [comment]
You can declare an `IBoutlet Collection` with all those `UIImageView`s instead of using them separately and declare another tuple array with x and y respecting the order.
